import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: "#fafafa",
    },
    container: {
        padding: 20,
        backgroundColor: "#fafafa",
    },
    header: {
        fontSize: 22,
        fontWeight: "700",
        textAlign: "center",
        color: "#D70F17",
        marginBottom: 20,
    },
    cartItem: {
        backgroundColor: "#fff",
        borderRadius: 12,
        paddingVertical: 12,
        paddingHorizontal: 16,
        marginBottom: 10,
        shadowColor: "#000",
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    itemName: {
        fontSize: 15,
        color: "#333",
        flex: 1,
        marginRight: 10,
        fontWeight: "500",
    },
    itemPrice: {
        fontSize: 15,
        color: "#D70F17",
        fontWeight: "600",
    },
    totalContainer: {
        backgroundColor: "#fff",
        borderRadius: 12,
        paddingVertical: 16,
        paddingHorizontal: 20,
        marginTop: 15,
        shadowColor: "#000",
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
        flexDirection: "row",
        justifyContent: "space-between",
    },
    totalLabel: {
        fontSize: 17,
        color: "#555",
        fontWeight: "500",
    },
    totalPrice: {
        fontSize: 18,
        fontWeight: "700",
        color: "#D70F17",
    },
    section: {
        marginTop: 28,
        backgroundColor: "#fff",
        borderRadius: 12,
        paddingVertical: 18,
        paddingHorizontal: 20,
        shadowColor: "#000",
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    sectionTitle: {
        fontSize: 17,
        fontWeight: "600",
        color: "#333",
        marginBottom: 12,
    },
    input: {
        backgroundColor: "#fefefe",
        borderWidth: 1,
        borderColor: "#ddd",
        borderRadius: 10,
        paddingHorizontal: 15,
        paddingVertical: 10,
        fontSize: 15,
        color: "#333",
        marginBottom: 12,
    },
    orderButton: {
        backgroundColor: "#D70F17",
        borderRadius: 10,
        paddingVertical: 14,
        marginTop: 24,
        shadowColor: "#D70F17",
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
    },
    orderText: {
        textAlign: "center",
        color: "#fff",
        fontWeight: "700",
        fontSize: 16,
    },
    logo: {
        width: 120,
        height: 120,
        resizeMode: "contain",
        alignSelf: "center",
        marginBottom: 8,
        marginTop: 4,
    },

});
