import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    button: {
        position: 'absolute',
        backgroundColor: '#D70F17',
        width: 60,
        height: 60,
        borderRadius: 30,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 8,
        zIndex: 1000,
    },
    badge: {
        position: 'absolute',
        top: -4,
        right: -4,
        backgroundColor: '#FFC72C',
        borderRadius: 12,
        width: 24,
        height: 24,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: 'white'
    },
    badgeText: {
        fontSize: 12,
        fontWeight: 'bold',
        color: '#D70F17',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.6)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContainer: {
        width: '90%',
        maxHeight: '80%',
        backgroundColor: 'white',
        borderRadius: 20,
        overflow: 'hidden',
    },
    modalHeader: {
        backgroundColor: '#FFC72C',
        paddingVertical: 15,
        paddingHorizontal: 20,
        alignItems: 'center',
        position: 'relative',
    },
    headerText: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#333',
    },
    closeBtn: {
        position: 'absolute',
        top: 10,
        left: 10,
        zIndex: 1,
    },
    flatListContent: {
        paddingVertical: 10,
    },
    itemContainer: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        paddingHorizontal: 15,
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
        position: 'relative',
    },
    itemImage: {
        width: 60,
        height: 60,
        borderRadius: 8,
        marginRight: 10,
    },
    itemContent: {
        flex: 1,
        flexDirection: 'column',
        justifyContent: 'space-between',
    },
    itemDetails: {
        marginBottom: 5,
    },
    itemName: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#333',
    },
    itemDescription: {
        fontSize: 12,
        color: '#666',
    },
    itemTotalPrice: {
        position: 'absolute',
        top: 15,
        right: 15,
        fontSize: 16,
        fontWeight: 'bold',
        color: '#D70F17',
    },
    itemActions: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        width: '100%',
    },
    quantityControl: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#D70F17',
        borderRadius: 5,
    },
    qtyButton: {
        paddingHorizontal: 10,
        paddingVertical: 5,
    },
    qtyButtonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: 'bold',
    },
    qtyText: {
        fontSize: 14,
        fontWeight: 'bold',
        color: 'white',
        paddingHorizontal: 8,
    },
    editDeleteButtons: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    editButton: {
        backgroundColor: '#FFC72C',
        padding: 8,
        borderRadius: 5,
        marginRight: 5,
    },
    deleteButton: {
        backgroundColor: '#FFC72C',
        padding: 8,
        borderRadius: 5,
    },
    emptyText: {
        textAlign: 'center',
        padding: 40,
        fontSize: 16,
        color: '#666',
    },
    footer: {
        padding: 15,
        borderTopWidth: 1,
        borderTopColor: '#f0f0f0',
    },
    totalContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 15,
    },
    totalLabel: {
        fontSize: 18,
        color: '#333',
    },
    totalPrice: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#D70F17',
    },
    footerButtons: {
        flexDirection: 'row',
    },
    addMoreButton: {
        flex: 1,
        backgroundColor: '#FFC72C',
        padding: 15,
        borderRadius: 10,
        alignItems: 'center',
        marginRight: 10,
    },
    checkoutBtn: {
        flex: 1,
        backgroundColor: '#D70F17',
        padding: 15,
        borderRadius: 10,
        alignItems: 'center',
    },
    buttonText: {
        color: '#333',
        fontWeight: 'bold',
        fontSize: 16,
    },
});