import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fff' },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: { alignItems: 'center', paddingVertical: 20 },
  logo: { width: 80, height: 80, borderRadius: 20, marginBottom: 10 },
  welcome: { fontSize: 20, fontWeight: '700', color: '#000' }, 
  subText: { color: '#555' },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fb5252ff',
    marginHorizontal: 20,
    paddingHorizontal: 10,
    borderRadius: 10,
    marginBottom: 20,
  },
  input: { flex: 1, marginLeft: 10, height: 40, color: '#000' },
  bannerContainer: { marginBottom: 15 },
  banner: { width: width - 40, height: 160, marginHorizontal: 10, borderRadius: 15 },
  sectionTitle: { fontSize: 18, fontWeight: '700', marginLeft: 20, marginBottom: 10, color: '#000' }, 
  categoryCard: { alignItems: 'center', marginHorizontal: 10 },
  categoryImage: { width: 80, height: 80, borderRadius: 10, backgroundColor: '#f0f0f0' },
  categoryText: { marginTop: 5, fontWeight: '600', color: '#000' },
  productContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
    paddingBottom: 20,
  },
  productCard: {
    width: width / 2.3,
    backgroundColor: '#fb5252ff',
    borderRadius: 15,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 5,
    elevation: 3,
    marginBottom: 15,
    padding: 10,
    alignItems: 'center',
  },
  productImage: { width: 100, height: 100, borderRadius: 10, backgroundColor: '#f0f0f0' },
  productName: { marginTop: 8, fontWeight: '600', textAlign: 'center', color: '#000' },
  productPrice: { color: 'black', fontWeight: '700', marginTop: 5 },
});