import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: '#fff' },
    container: { paddingBottom: 150 },
    imageHeader: { width: '100%', height: 300, resizeMode: 'cover' },
    backButton: {
        position: 'absolute',
        top: 50,
        left: 20,
        zIndex: 10,
        backgroundColor: 'rgba(0,0,0,0.5)',
        borderRadius: 20,
        width: 40,
        height: 40,
        justifyContent: 'center',
        alignItems: 'center',
    },
    infoContainer: { padding: 20 },
    productName: { fontSize: 28, fontWeight: 'bold', color: '#333', marginBottom: 8 },
    productPrice: { fontSize: 24, fontWeight: '700', color: '#D70F17', marginBottom: 16 },
    productDescription: { fontSize: 16, color: '#666', lineHeight: 24 },
    quantityContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginVertical: 20,
    },
    quantityButton: {
        width: 50,
        height: 50,
        backgroundColor: '#f0f0f0',
        borderRadius: 25,
        justifyContent: 'center',
        alignItems: 'center',
    },
    quantityButtonText: { fontSize: 24, color: '#333' },
    quantityText: { fontSize: 22, fontWeight: 'bold', marginHorizontal: 20 },
    footer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: 'white',
        padding: 20,
        borderTopWidth: 1,
        borderTopColor: 'red',
    },
    totalContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 15,
    },
    totalLabel: { fontSize: 18, color: '#666' },
    totalPrice: { fontSize: 20, fontWeight: 'bold', color: '#D70F17' },
    actionButtons: { flexDirection: 'row', justifyContent: 'space-between' },
    addToCartButton: {
        backgroundColor: '#FFC72C',
        paddingVertical: 15,
        borderRadius: 8,
        flex: 1,
        alignItems: 'center',
        marginRight: 10,
    },
    buyNowButton: {
        backgroundColor: '#D70F17',
        marginRight: 0,
    },
    buttonText: {
        color: 'white',
        fontWeight: 'bold',
        fontSize: 16,
    },
});
